theme: jekyll-theme-hacker
title: Joe Alisson's Personal Place
description: Used to document my studies cases and work
show_downloads: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
